---

- name: Collect static pages
  django_manage: app_path={{ project_dir }} command=collectstatic virtualenv={{ root_dir }}/venv

# - name: Create Wagtail Super User 
#   shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('{{superuser_username}}', '{{ superuser_email }}', '{{superuser_password}}')" | {{ root_dir }}/venv/bin/python3 {{project_dir}}/manage.py shell

- name: Create Wagtail Super User 
  command: "{{ root_dir }}/venv/bin/python3 {{ root_dir }}/ansible/scripts/superuser.py {{superuser_username}} {{ superuser_email }} {{superuser_password}}"

  
