---

- name: Install python and other dependencies
  apt: pkg={{item}} state=latest
  with_items:
    - python3
    - python3-pip
    - python3-venv
    - virtualenv
    - libmysqlclient-dev
    - supervisor
  become: true