---

- name: Copy supervisor config file
  template: src=wagtail.conf.j2 dest=/etc/supervisor/conf.d/{{project_name}}.conf
  become: true

- name: Run supervisor app
  supervisorctl: 
    name: "{{project_name}}" 
    state: present
  become: true
