---

- name: Is root password set? 
  command: mysql -u root --execute "SELECT NOW()" 
  register: is_root_password_set 
  ignore_errors: yes

- name: Set root password 
  mysql_user: user=root password="{{mysql_root_password}}" host=localhost
  when: is_root_password_set.rc == 0

- name: Create myapp database 
  mysql_db: 
    name: "{{mysql_db}}"  
    login_user: root 
    login_password: "{{mysql_root_password}}" 
    login_host: localhost 
    state: present
  when: is_root_password_set.rc == 0