---

- name: Set root password 
  mysql_user: user=root password="{{mysql_root_password}}" host=localhost

- name: Create myapp database 
  mysql_db: 
    name: "{{db_name}}"  
    login_user: root 
    login_password: "{{mysql_root_password}}" 
    login_host: localhost 
    state: present