---
# tasks file for maria-db

- name: Install dependencies
  include_tasks: dependencies.yml
  become: true

- name: add offical maria-db repository
  include_tasks: add-repository.yml
  become: true

- name: Install and run maria-db
  include_tasks: install.yml
  become: true

- name: config maria-db - set root password and create database
  include_tasks: config.yml
  become: true